from src.forms.registry import register_schema, FormSchema, FormFieldDefinition, ExtractionTier

@register_schema("1120-S", 2023)
def schema_1120s_2023() -> FormSchema:
    return FormSchema(
        form_id="1120-S",
        display_name="Form 1120-S (U.S. Income Tax Return for an S Corporation)",
        detection_patterns=[
            "Form 1120-S",
            "U.S. Income Tax Return for an S Corporation",
        ],
        fields=[
            # Identity (Box A-I)
            FormFieldDefinition("ein", ["EIN", "Employer identification number"], value_type="ssn"),
            FormFieldDefinition("corporation_name", ["Name"], value_type="str"),
            FormFieldDefinition("address", ["Number and street"], value_type="str", optional=True),
            FormFieldDefinition("city", ["City or town"], value_type="str", optional=True),
            FormFieldDefinition("state", ["State or province"], value_type="str", optional=True),
            FormFieldDefinition("zip", ["ZIP or foreign postal code"], value_type="str", optional=True),
            FormFieldDefinition("s_election_date", ["A S election effective date"], value_type="date", optional=True),
            FormFieldDefinition("business_activity_code", ["B Business activity code"], value_type="str", optional=True),
            FormFieldDefinition("date_incorporated", ["E Date incorporated"], value_type="date", optional=True),
            FormFieldDefinition("total_assets", ["F Total assets"], value_type="currency", optional=True),
            FormFieldDefinition("number_of_shareholders", ["I Enter the number of shareholders"], value_type="int", optional=True),
            
            # Page 1 Income
            FormFieldDefinition("gross_receipts_line_1a", ["1a Gross receipts or sales"], value_type="currency"),
            FormFieldDefinition("returns_allowances_line_1b", ["1b Less returns and allowances"], value_type="currency", optional=True),
            FormFieldDefinition("cost_of_goods_sold_line_2", ["2 Cost of goods sold"], value_type="currency", optional=True),
            FormFieldDefinition("gross_profit_line_3", ["3 Gross profit"], value_type="currency", optional=True),
            FormFieldDefinition("net_gain_loss_line_4", ["4 Net gain (loss)"], value_type="currency", optional=True),
            FormFieldDefinition("other_income_line_5", ["5 Other income (loss)"], value_type="currency", optional=True),
            FormFieldDefinition("total_income_line_6", ["6 Total income (loss)"], value_type="currency"),
            
            # Page 1 Deductions
            FormFieldDefinition("compensation_officers_line_7", ["7 Compensation of officers"], value_type="currency", optional=True),
            FormFieldDefinition("salaries_wages_line_8", ["8 Salaries and wages"], value_type="currency", optional=True),
            FormFieldDefinition("repairs_maintenance_line_9", ["9 Repairs and maintenance"], value_type="currency", optional=True),
            FormFieldDefinition("bad_debts_line_10", ["10 Bad debts"], value_type="currency", optional=True),
            FormFieldDefinition("rents_line_11", ["11 Rents"], value_type="currency", optional=True),
            FormFieldDefinition("taxes_licenses_line_12", ["12 Taxes and licenses"], value_type="currency", optional=True),
            FormFieldDefinition("interest_line_13", ["13 Interest"], value_type="currency", optional=True),
            FormFieldDefinition("depreciation_line_14", ["14 Depreciation"], value_type="currency", optional=True),
            FormFieldDefinition("depletion_line_15", ["15 Depletion"], value_type="currency", optional=True),
            FormFieldDefinition("advertising_line_16", ["16 Advertising"], value_type="currency", optional=True),
            FormFieldDefinition("pension_plans_line_17", ["17 Pension, profit-sharing"], value_type="currency", optional=True),
            FormFieldDefinition("employee_benefit_line_18", ["18 Employee benefit"], value_type="currency", optional=True),
            FormFieldDefinition("energy_deduction_line_19", ["19 Energy efficient"], value_type="currency", optional=True),
            FormFieldDefinition("other_deductions_line_20", ["20 Other deductions"], value_type="currency", optional=True),
            FormFieldDefinition("total_deductions_line_21", ["21 Total deductions"], value_type="currency"),
            
            # Page 1 Totals & Tax
            FormFieldDefinition("ordinary_business_income_loss_line_22", ["22 Ordinary business income"], value_type="currency"),
            FormFieldDefinition("excess_passive_tax_line_23a", ["23a Excess net passive income"], value_type="currency", optional=True),
            FormFieldDefinition("schedule_d_tax_line_23b", ["23b Tax from Schedule D"], value_type="currency", optional=True),
            FormFieldDefinition("total_tax_line_23c", ["23c Add lines 23a and 23b"], value_type="currency", optional=True),
            FormFieldDefinition("estimated_tax_payments_line_24a", ["24a Current year’s estimated tax"], value_type="currency", optional=True),
            FormFieldDefinition("tax_deposited_7004_line_24b", ["24b Tax deposited with Form 7004"], value_type="currency", optional=True),
            FormFieldDefinition("fuel_tax_credit_line_24c", ["24c Credit for federal tax paid on fuels"], value_type="currency", optional=True),
            FormFieldDefinition("total_payments_line_24z", ["24z Add lines 24a through 24d"], value_type="currency", optional=True),
            FormFieldDefinition("estimated_tax_penalty_line_25", ["25 Estimated tax penalty"], value_type="currency", optional=True),
            FormFieldDefinition("amount_owed_line_26", ["26 Amount owed"], value_type="currency", optional=True),
            FormFieldDefinition("overpayment_line_27", ["27 Overpayment"], value_type="currency", optional=True),
            
            # Schedule K (Page 3)
            FormFieldDefinition("k_ordinary_income_line_1", ["1 Ordinary business income (loss)"], value_type="currency", optional=True),
            FormFieldDefinition("k_rental_income_line_2", ["2 Net rental real estate"], value_type="currency", optional=True),
            FormFieldDefinition("k_interest_income_line_4", ["4 Interest income"], value_type="currency", optional=True),
            FormFieldDefinition("k_ordinary_dividends_line_5a", ["5a Ordinary dividends"], value_type="currency", optional=True),
            FormFieldDefinition("k_qualified_dividends_line_5b", ["5b Qualified dividends"], value_type="currency", optional=True),
            FormFieldDefinition("k_royalties_line_6", ["6 Royalties"], value_type="currency", optional=True),
            FormFieldDefinition("k_net_short_term_gain_line_7", ["7 Net short-term capital gain"], value_type="currency", optional=True),
            FormFieldDefinition("k_net_long_term_gain_line_8a", ["8a Net long-term capital gain"], value_type="currency", optional=True),
            FormFieldDefinition("k_section_179_deduction_line_11", ["11 Section 179 deduction"], value_type="currency", optional=True),
            FormFieldDefinition("k_distributions_line_16d", ["16d Distributions"], value_type="currency", optional=True),

            # Schedule B (Page 2) - Other Information
            FormFieldDefinition("sch_b_q1a_yes", ["1a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q1a_no", ["1a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q1b_yes", ["1b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q1b_no", ["1b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q2_yes", ["2 Own directly an interest of 20%"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q2_no", ["2 Own directly an interest of 20%"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q3_yes", ["3"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q3_no", ["3"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q4a_yes", ["4a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q4a_no", ["4a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q4b_yes", ["4b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q4b_no", ["4b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q5a_yes", ["5a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q5a_no", ["5a"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q5a_i", ["(i) Total shares of restricted stock"], value_type="int", optional=True),
            FormFieldDefinition("sch_b_q5a_ii", ["(ii) Total shares of non-restricted stock"], value_type="int", optional=True),
            FormFieldDefinition("sch_b_q5b_yes", ["5b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q5b_no", ["5b"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q5b_i", ["(i) Total shares of stock outstanding"], value_type="int", optional=True),
            FormFieldDefinition("sch_b_q5b_ii", ["(ii) Total shares of stock outstanding if"], value_type="int", optional=True),
            FormFieldDefinition("sch_b_q6_yes", ["6 Has this corporation filed, or is it required"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q6_no", ["6 Has this corporation filed, or is it required"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q7_checkbox", ["7 Check this box if the corporation issued"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q8_yes", ["8 If the corporation"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q8_no", ["8 If the corporation"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q8_amount", ["8 If the corporation"], value_type="currency", optional=True),
            FormFieldDefinition("sch_b_q9_yes", ["9 Did the corporation have an election under section 163"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q9_no", ["9 Did the corporation have an election under section 163"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q10_yes", ["10 Does the corporation satisfy one or more"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q10_no", ["10 Does the corporation satisfy one or more"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q11_yes", ["11 Does the corporation satisfy both"], value_type="boolean", optional=True),
            FormFieldDefinition("sch_b_q11_no", ["11 Does the corporation satisfy both"], value_type="boolean", optional=True),

            # Schedule K (Continued - Page 3)
            FormFieldDefinition("k_investment_income_line_17a", ["17a Investment income"], value_type="currency", optional=True),
            FormFieldDefinition("k_investment_expenses_line_17b", ["17b Investment expenses"], value_type="currency", optional=True),
            FormFieldDefinition("k_dividend_distributions_line_17c", ["17c Dividend distributions paid from accumulated earnings"], value_type="currency", optional=True),
            FormFieldDefinition("k_other_items_line_17d", ["17d Other items and amounts"], value_type="currency", optional=True),
            FormFieldDefinition("k_income_reconciliation_line_18", ["18 Income (loss) reconciliation"], value_type="currency", optional=True),

            # Schedule L (Page 4) - Balance Sheets
            # Assets
            FormFieldDefinition("sch_l_cash_line_1_begin", ["1 Cash"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_cash_line_1_end", ["1 Cash"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_trade_notes_line_2a_begin", ["2a Trade notes and accounts receivable"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_trade_notes_line_2a_end", ["2a Trade notes and accounts receivable"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_bad_debts_allowance_line_2b_begin", ["b Less allowance for bad debts"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_bad_debts_allowance_line_2b_end", ["b Less allowance for bad debts"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_inventories_line_3_begin", ["3 Inventories"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_inventories_line_3_end", ["3 Inventories"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_us_gov_obligations_line_4_begin", ["4 U.S. government obligations"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_us_gov_obligations_line_4_end", ["4 U.S. government obligations"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_tax_exempt_securities_line_5_begin", ["5 Tax-exempt securities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_tax_exempt_securities_line_5_end", ["5 Tax-exempt securities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_current_assets_line_6_begin", ["6 Other current assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_current_assets_line_6_end", ["6 Other current assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_loans_to_shareholders_line_7_begin", ["7 Loans to shareholders"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_loans_to_shareholders_line_7_end", ["7 Loans to shareholders"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgage_real_estate_loans_line_8_begin", ["8 Mortgage and real estate loans"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgage_real_estate_loans_line_8_end", ["8 Mortgage and real estate loans"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_investments_line_9_begin", ["9 Other investments"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_investments_line_9_end", ["9 Other investments"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_buildings_depreciable_assets_line_10a_begin", ["10a Buildings and other depreciable assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_buildings_depreciable_assets_line_10a_end", ["10a Buildings and other depreciable assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_depreciation_line_10b_begin", ["b Less accumulated depreciation"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_depreciation_line_10b_end", ["b Less accumulated depreciation"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_depletable_assets_line_11a_begin", ["11a Depletable assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_depletable_assets_line_11a_end", ["11a Depletable assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_depletion_line_11b_begin", ["b Less accumulated depletion"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_depletion_line_11b_end", ["b Less accumulated depletion"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_land_line_12_begin", ["12 Land"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_land_line_12_end", ["12 Land"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_intangible_assets_line_13a_begin", ["13a Intangible assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_intangible_assets_line_13a_end", ["13a Intangible assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_amortization_line_13b_begin", ["b Less accumulated amortization"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accumulated_amortization_line_13b_end", ["b Less accumulated amortization"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_assets_line_14_begin", ["14 Other assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_assets_line_14_end", ["14 Other assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_total_assets_line_15_begin", ["15 Total assets"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_total_assets_line_15_end", ["15 Total assets"], value_type="currency", optional=True),
            
            # Liabilities and Equity
            FormFieldDefinition("sch_l_accounts_payable_line_16_begin", ["16 Accounts payable"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_accounts_payable_line_16_end", ["16 Accounts payable"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgages_notes_under_1yr_line_17_begin", ["17 Mortgages, notes, bonds payable in less than 1 year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgages_notes_under_1yr_line_17_end", ["17 Mortgages, notes, bonds payable in less than 1 year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_current_liabilities_line_18_begin", ["18 Other current liabilities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_current_liabilities_line_18_end", ["18 Other current liabilities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_loans_from_shareholders_line_19_begin", ["19 Loans from shareholders"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_loans_from_shareholders_line_19_end", ["19 Loans from shareholders"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgages_notes_over_1yr_line_20_begin", ["20 Mortgages, notes, bonds payable in 1 year or more"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_mortgages_notes_over_1yr_line_20_end", ["20 Mortgages, notes, bonds payable in 1 year or more"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_liabilities_line_21_begin", ["21 Other liabilities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_other_liabilities_line_21_end", ["21 Other liabilities"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_capital_stock_line_22_begin", ["22 Capital stock"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_capital_stock_line_22_end", ["22 Capital stock"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_additional_paid_in_capital_line_23_begin", ["23 Additional paid-in capital"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_additional_paid_in_capital_line_23_end", ["23 Additional paid-in capital"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_retained_earnings_line_24_begin", ["24 Retained earnings"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_retained_earnings_line_24_end", ["24 Retained earnings"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_adjustments_to_equity_line_25_begin", ["25 Adjustments to shareholders' equity"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_adjustments_to_equity_line_25_end", ["25 Adjustments to shareholders' equity"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_less_cost_treasury_stock_line_26_begin", ["26 Less cost of treasury stock"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_less_cost_treasury_stock_line_26_end", ["26 Less cost of treasury stock"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_total_liabilities_equity_line_27_begin", ["27 Total liabilities and shareholders' equity"], value_type="currency", optional=True),
            FormFieldDefinition("sch_l_total_liabilities_equity_line_27_end", ["27 Total liabilities and shareholders' equity"], value_type="currency", optional=True),

            # Schedule M-1 (Page 5)
            FormFieldDefinition("sch_m1_net_income_books_line_1", ["1 Net income (loss) per books"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_income_on_k_not_books_line_2", ["2 Income included on Schedule K"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_expenses_books_not_k_line_3", ["3 Expenses recorded on books this year not included on Schedule K"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_depreciation_line_3a", ["a Depreciation"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_travel_entertainment_line_3b", ["b Travel and entertainment"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_add_lines_1_to_3_line_4", ["4 Add lines 1 through 3"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_income_books_not_k_line_5", ["5 Income recorded on books this year not included on Schedule K"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_tax_exempt_interest_line_5a", ["a Tax-exempt interest"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_deductions_k_not_books_line_6", ["6 Deductions included on Schedule K"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_depreciation_line_6a", ["a Depreciation"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_add_lines_5_and_6_line_7", ["7 Add lines 5 and 6"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m1_income_reconciliation_line_8", ["8 Income (loss) (Schedule K, line 18)"], value_type="currency", optional=True),

            # Schedule M-2 (Page 5)
            FormFieldDefinition("sch_m2_balance_beginning_line_1_col_a", ["1 Balance at beginning of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_beginning_line_1_col_b", ["1 Balance at beginning of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_beginning_line_1_col_c", ["1 Balance at beginning of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_beginning_line_1_col_d", ["1 Balance at beginning of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_ordinary_income_line_2_col_a", ["2 Ordinary income from page 1"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_ordinary_income_line_2_col_b", ["2 Ordinary income from page 1"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_ordinary_income_line_2_col_c", ["2 Ordinary income from page 1"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_ordinary_income_line_2_col_d", ["2 Ordinary income from page 1"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_additions_line_3_col_a", ["3 Other additions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_additions_line_3_col_b", ["3 Other additions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_additions_line_3_col_c", ["3 Other additions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_additions_line_3_col_d", ["3 Other additions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_loss_line_4_col_a", ["4 Loss from page 1, line 22"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_loss_line_4_col_b", ["4 Loss from page 1, line 22"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_loss_line_4_col_c", ["4 Loss from page 1, line 22"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_loss_line_4_col_d", ["4 Loss from page 1, line 22"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_reductions_line_5_col_a", ["5 Other reductions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_reductions_line_5_col_b", ["5 Other reductions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_reductions_line_5_col_c", ["5 Other reductions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_other_reductions_line_5_col_d", ["5 Other reductions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_combine_line_6_col_a", ["6 Combine lines 1 through 5"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_combine_line_6_col_b", ["6 Combine lines 1 through 5"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_combine_line_6_col_c", ["6 Combine lines 1 through 5"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_combine_line_6_col_d", ["6 Combine lines 1 through 5"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_distributions_line_7_col_a", ["7 Distributions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_distributions_line_7_col_b", ["7 Distributions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_distributions_line_7_col_c", ["7 Distributions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_distributions_line_7_col_d", ["7 Distributions"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_end_line_8_col_a", ["8 Balance at end of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_end_line_8_col_b", ["8 Balance at end of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_end_line_8_col_c", ["8 Balance at end of tax year"], value_type="currency", optional=True),
            FormFieldDefinition("sch_m2_balance_end_line_8_col_d", ["8 Balance at end of tax year"], value_type="currency", optional=True),
        ],
        extraction_tier=ExtractionTier.PDFPLUMBER,
    )
